type User {
    id: ID!
    name: String!
    email: String!
    active: Boolean!
    image: String
}

type Post {
    id: ID!
    title: String!
    description: String!
    images: [String]
    user: User!
}
type Notification {
    id: ID!
    receiver: User!
    sender: User!
    post: Post
    type: NotificationType!
    body: String!
    read: Boolean!
    createdAt: String!
}

enum NotificationType {
    FOLLOW
    LIKE
    COMMENT
}
input UserInput {
    name: String!
    email: String!
    password: String!
}

input LoginInput {
    email: String!
    password: String!
}

input ChangePasswordInput {
    oldPassword: String!
    newPassword: String!
}

input PostInput {
    title: String!
    description: String!
    comment: [String]
    images: [String]
}

input VerifyCodeInput {
    email: String!
    code: String!
}

type Query {
    user: User
    users: [User]

    myPosts: [Post]
    posts: [Post]
}

type Mutation {

    generateActivateUserCode(
        input: UserInput!
    ): String

    login(
        input: LoginInput!
    ): String

    activateUser(
        email: String!
        code: String!
    ): Boolean

    generatePasswordResetCode: String

    changePassword(
        email: String!
        code: String!
        input: ChangePasswordInput!
    ): Boolean

    deleteUser: Boolean

    createPost(
        input: PostInput!
    ): Post

    updatePost(
        id: ID!
        input: PostInput!
    ): Post

    deletePost(
        id: ID!
    ): Boolean
}